### ISSUE TITLE
Results for WWT Autocorrelation and Attribute Distribution for doppelganger_pytorch.ipynb could not be reproduced for pytorch_fast

### ISSUE THREAD

**Issue by rllyryan** [gretelai/public_research#7]
Dear repository owners,

![image](https://github.com/gretelai/public_research/assets/72377011/cce44d61-3c46-4460-99ce-c8556dd5a1c8)
![image](https://github.com/gretelai/public_research/assets/72377011/91c05ba0-c338-43c8-a320-ad5b3d247c2c)

I could not replicate the auto-correlation figure for the WWT dataset in the doppelganger_pytorch.ipynb notebook, could I ask why this is so? (I ran the notebook as it is)

I used Google Colab's V100 and A100 GPU hardwares. Not sure if it is due to some update in Pytorch or something else entirely.

Edited:
![image](https://github.com/gretelai/public_research/assets/72377011/5e2d5442-f9ac-4cfa-80c7-6333ce40fbf3)

This was different from the one shown in the notebook with greater number of barcharts.

Thank you!

**Comment by kboyd** [comment]
I'm not sure what's going on with the DGAN model on this data. I see the same poorer quality from the notebook across a few setups. Will need to investigate further.

Thanks for trying out our notebooks!

**Comment by rllyryan** [comment]
> I'm not sure what's going on with the DGAN model on this data. I see the same poorer quality from the notebook across a few setups. Will need to investigate further.
> 
> Thanks for trying out our notebooks!

Thank you for taking a look into this! Maybe it could be due to the dynamic nature of Google Colab, things don't always go right on that web IDE.

Please do let me know when it is ready to be tested again! Have a great week ahead :)

**Comment by kboyd** [comment]
Notebook is updated and should work as expected now.

We improved the `gretel-synthetics` package to return DataFrame columns in the same order as the training data, but hadn't updated the notebook. So it was using the wrong columns from the synthetic DataFrame to create the charts. The model was working fine, the visualization was off. But that's fixed in the notebook now.
